# Copyright (C) 2015 TeamEOS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/r5/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter r5,$(TARGET_DEVICE)),)

include $(CLEAR_VARS)
LOCAL_MODULE := libtime_genoff
LOCAL_MODULE_OWNER := oppo
LOCAL_SRC_FILES := proprietary/vendor/lib/libtime_genoff.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)

# Create target dirs if needed
$(shell mkdir -p $(TARGET_OUT)/bin)
$(shell mkdir -p $(TARGET_OUT)/etc/firmware)
$(shell mkdir -p $(TARGET_OUT)/lib/egl)
$(shell mkdir -p $(TARGET_OUT)/lib/hw)
$(shell mkdir -p $(TARGET_OUT)/vendor/lib/egl)

# Copy the blobs
$(shell cp -Rf $(LOCAL_PATH)/proprietary/bin $(TARGET_OUT)/bin/)
$(shell cp -Rf $(LOCAL_PATH)/proprietary/etc/firmware $(TARGET_OUT)/etc/firmware/)
$(shell cp -Rf $(LOCAL_PATH)/proprietary/lib $(TARGET_OUT)/lib/)
$(shell cp -Rf $(LOCAL_PATH)/proprietary/lib/egl $(TARGET_OUT)/lib/egl/)
$(shell cp -Rf $(LOCAL_PATH)/proprietary/lib/hw $(TARGET_OUT)/lib/hw/)
$(shell cp -Rf $(LOCAL_PATH)/proprietary/vendor/lib $(TARGET_OUT)/vendor/lib/)
$(shell cp -Rf $(LOCAL_PATH)/proprietary/vendor/lib/egl $(TARGET_OUT)/vendor/lib/egl)

endif

